steps:
# Unit Test
- name: 'gcr.io/cloud-builders/mvn'
  args: ['test']
# Build Container
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
  - build
  - --builder=gcr.io/buildpacks/builder
  - --publish
  - us-central1-docker.pkg.dev/container-developer/repo/helloworld:$COMMIT_SHA
# Create Release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - -c
  - |
    gcloud deploy releases create test-release-$SHORT_SHA \
    --project=container-developer \
    --region=us-central1 \
    --delivery-pipeline=my-gke-demo-app-1 \
    --images=us-central1-docker.pkg.dev/container-developer/repo/helloworld=us-central1-docker.pkg.dev/container-developer/repo/helloworld@$(gcloud artifacts docker images describe us-central1-docker.pkg.dev/container-developer/repo/helloworld:"$COMMIT_SHA" --format "value(image_summary.digest)")
