steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - -c
  - |
    pack build --builder=gcr.io/buildpacks/builder --publish --quiet us-central1-docker.pkg.dev/container-developer/repo/helloworld:$COMMIT_SHA > /workspace/image-with-digest.txt

#- name: "gcr.io/cloud-builders/gke-deploy"
#  args:
#  - run
#  - --filename=k8s/helloworld.yml
#  - --image=us-central1-docker.pkg.dev/container-developer/repo/helloworld:$COMMIT_SHA
#  - --location=us-central1
#  - --cluster=dev

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud deploy releases create test-release-$SHORT_SHA --project=container-developer --region=us-central1 --delivery-pipeline=my-gke-demo-app-1 --images=helloworld:$(cat /workspace/image-with-digest.txt)