apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles: []
    strategy:
      standard:
        verify: true
  # - targetId: prod
  #   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/m2c-demo/locations/us-central1/clusters/autopilot-cluster-1

# ---

# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: prod
# description: prod cluster
# gke:
#   cluster: projects/container-developer/locations/us-central1/clusters/prod