steps:

# Unit Test
# - name: 'gcr.io/cloud-builders/mvn'
#   args: ['test']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - deploy
  - apply 
  - --file=clouddeploy.yaml
  - --region=us-central1

- name: 'gcr.io/k8s-skaffold/skaffold'
  entrypoint: 'skaffold'
  args:
  - build
  - --file-output=/workspace/artifacts.json

# TODO Integration Test

# TODO Security scan

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - -c
  - |
    gcloud deploy releases create helloworld-release-$SHORT_SHA \
    --project=m2c-demo \
    --region=us-central1 \
    --delivery-pipeline=my-gke-demo-app-1 \
    --build-artifacts=/workspace/artifacts.json
    
