steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['test']

- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
  - build
  - --builder=gcr.io/buildpacks/builder
#  - --publish
  - us-central1-docker.pkg.dev/container-developer/repo/helloworld:$COMMIT_SHA

#- name: "gcr.io/cloud-builders/gke-deploy"
#  args:
#  - run
#  - --filename=k8s/helloworld.yml
#  - --image=us-central1-docker.pkg.dev/container-developer/repo/helloworld:$COMMIT_SHA
#  - --location=us-central1
#  - --cluster=dev

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - -c
  - |
    gcloud deploy releases create \
    test-release-$SHORT_SHA \
    --project=container-developer \
    --region=us-central1 \
    --delivery-pipeline=my-gke-demo-app-1 \
    --images=helloworld=us-central1-docker.pkg.dev/container-developer/repo/helloworld@$(gcloud builds describe $BUILD_ID --format 'value(results.images[0].digest)')

images: [us-central1-docker.pkg.dev/container-developer/repo/helloworld:$COMMIT_SHA]