apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/helloworld
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
    # jib:
    #   project: com.example:demo
    #   type: maven
    #   args:
    #   - --no-transfer-progress
    #   - -Psync
    #   - -DskipTests
    #   fromImage: gcr.io/distroless/java:debug
    sync:
      auto: true
kubectl:
  manifests:
    - k8s/helloworld.yml

# deploy:
#   kubectl:
#     manifests:
#     - k8s/*
# portForward:
# - resourceType: service
#   resourceName: helloworld
#   port: 80