apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/m2c-demo/container/helloworld
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
#            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld
spec:
  selector:
    app: helloworld
  ports:
  - port: 80
    targetPort: 8080
    name: web
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: helloworld-monitor
  namespace: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 30s