apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: satelite
        imagePullPolicy: Always
        image: helloworld
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000"

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: helloworld
#spec:
#  selector:
#    app: helloworld
#  ports:
#  - port: 80
#    targetPort: 8080